// export const BASE_URL = "http://ec2-54-188-60-94.us-west-2.compute.amazonaws.com/"
export const BASE_URL = "http://localhost:8888/cats/"

export const ADD_CAT_PIC = "ADD_CAT_PIC"
export const CHECK_USERNAME = "CHECK_USERNAME"
export const FETCH_USER = "FETCH_USER"
export const GET_CAT = "GET_CAT"
export const LIKE_CAT = "LIKE_CAT"
export const LOGOUT = "LOGOUT"
export const REGISTER = "REGISTER"
export const RESET_CAT = "RESET_CAT"
export const SEARCH_CATS_BY_LOCATION = "SEARCH_CATS_BY_LOCATION"
export const SEARCH_RESOURCES = "SEARCH_RESOURCES"
export const SET_USER_DATA = "SET_USER_DATA"
export const SET_REGION = "SET_REGION"
export const TOGGLE_CAT_EDITING_PAGE = "TOGGLE_CAT_EDITING_PAGE"
export const UNLIKE_CAT = "UNLIKE_CAT"
export const VERIFY_EMAIL = "VERIFY_EMAIL"
